// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	extensions: {
		/**
		 * E​x​t​e​n​s​i​o​n​s
		 */
		title: string
		/**
		 * D​o​w​n​l​o​a​d​ ​t​h​e​ ​T​e​s​t​a​u​s​t​i​m​e​ ​e​x​t​e​n​s​i​o​n​ ​f​o​r​ ​y​o​u​r​ ​f​a​v​o​r​i​t​e​ ​c​o​d​e​ ​e​d​i​t​o​r​!
		 */
		body: string
		/**
		 * D​o​w​n​l​o​a​d​ ​T​e​s​t​a​u​s​t​i​m​e​ ​f​o​r​ ​V​i​s​u​a​l​ ​S​t​u​d​i​o​ ​C​o​d​e
		 */
		vscode: string
		/**
		 * D​o​w​n​l​o​a​d​ ​T​e​s​t​a​u​s​t​i​m​e​ ​f​o​r​ ​N​e​o​v​i​m
		 */
		neovim: string
		/**
		 * D​o​w​n​l​o​a​d​ ​T​e​s​t​a​u​s​t​i​m​e​ ​f​o​r​ ​I​n​t​e​l​l​i​J
		 */
		intellij: string
		/**
		 * D​o​w​n​l​o​a​d​ ​T​e​s​t​a​u​s​t​i​m​e​ ​f​o​r​ ​M​i​c​r​o
		 */
		micro: string
	}
}

export type TranslationFunctions = {
	extensions: {
		/**
		 * Extensions
		 */
		title: () => LocalizedString
		/**
		 * Download the Testaustime extension for your favorite code editor!
		 */
		body: () => LocalizedString
		/**
		 * Download Testaustime for Visual Studio Code
		 */
		vscode: () => LocalizedString
		/**
		 * Download Testaustime for Neovim
		 */
		neovim: () => LocalizedString
		/**
		 * Download Testaustime for IntelliJ
		 */
		intellij: () => LocalizedString
		/**
		 * Download Testaustime for Micro
		 */
		micro: () => LocalizedString
	}
}

export type Formatters = {}
