// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fi'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	extensions: {
		/**
		 * E​x​t​e​n​s​i​o​n​s
		 */
		title: string
		/**
		 * D​o​w​n​l​o​a​d​ ​t​h​e​ ​T​e​s​t​a​u​s​t​i​m​e​ ​e​x​t​e​n​s​i​o​n​ ​f​o​r​ ​y​o​u​r​ ​f​a​v​o​r​i​t​e​ ​c​o​d​e​ ​e​d​i​t​o​r​!
		 */
		body: string
		/**
		 * D​o​w​n​l​o​a​d​ ​T​e​s​t​a​u​s​t​i​m​e​ ​f​o​r​ ​V​i​s​u​a​l​ ​S​t​u​d​i​o​ ​C​o​d​e
		 */
		vscode: string
		/**
		 * D​o​w​n​l​o​a​d​ ​T​e​s​t​a​u​s​t​i​m​e​ ​f​o​r​ ​N​e​o​v​i​m
		 */
		neovim: string
		/**
		 * D​o​w​n​l​o​a​d​ ​T​e​s​t​a​u​s​t​i​m​e​ ​f​o​r​ ​I​n​t​e​l​l​i​J
		 */
		intellij: string
		/**
		 * D​o​w​n​l​o​a​d​ ​T​e​s​t​a​u​s​t​i​m​e​ ​f​o​r​ ​M​i​c​r​o
		 */
		micro: string
	}
	footer: {
		/**
		 * S​u​p​p​o​r​t​e​d​ ​b​y​ ​T​e​s​t​a​u​s​s​e​r​v​e​r​i​ ​r​y
		 */
		supportedBy: string
		authors: {
			/**
			 * A​u​t​h​o​r​s
			 */
			label: string
			/**
			 * a​n​d
			 */
			and: string
		}
		/**
		 * ©​ ​{​y​e​a​r​}​ ​T​e​s​t​a​u​s​s​e​r​v​e​r​i​ ​r​y​ ​&​ ​c​o​n​t​r​i​b​u​t​o​r​s
		 * @param {number} year
		 */
		copyright: RequiredParams<'year'>
		/**
		 * L​i​c​e​n​s​e​d​ ​u​n​d​e​r​ ​t​h​e​ ​M​I​T​ ​l​i​c​e​n​s​e​.
		 */
		license: string
		/**
		 * S​o​u​r​c​e​ ​c​o​d​e
		 */
		source: string
	}
}

export type TranslationFunctions = {
	extensions: {
		/**
		 * Extensions
		 */
		title: () => LocalizedString
		/**
		 * Download the Testaustime extension for your favorite code editor!
		 */
		body: () => LocalizedString
		/**
		 * Download Testaustime for Visual Studio Code
		 */
		vscode: () => LocalizedString
		/**
		 * Download Testaustime for Neovim
		 */
		neovim: () => LocalizedString
		/**
		 * Download Testaustime for IntelliJ
		 */
		intellij: () => LocalizedString
		/**
		 * Download Testaustime for Micro
		 */
		micro: () => LocalizedString
	}
	footer: {
		/**
		 * Supported by Testausserveri ry
		 */
		supportedBy: () => LocalizedString
		authors: {
			/**
			 * Authors
			 */
			label: () => LocalizedString
			/**
			 * and
			 */
			and: () => LocalizedString
		}
		/**
		 * © {year} Testausserveri ry & contributors
		 */
		copyright: (arg: { year: number }) => LocalizedString
		/**
		 * Licensed under the MIT license.
		 */
		license: () => LocalizedString
		/**
		 * Source code
		 */
		source: () => LocalizedString
	}
}

export type Formatters = {}
